#
name: char-crypt
environment: dev

logging:
  level:
    .: debug
    org.springframework: DEBUG
    org.hibernate:
      SQL: DEBUG
      type.descriptor.sql: trace
  file:
    name: ${HOME}/logs/char-crypt.log

server:
  port: 5000

app:
  name: ${name}
  printing-mode-on: false
  base-package: io.github.astrapi69.charcrypt
  api-info-title: char-crypt REST API
  api-info-description: REST API char-crypt description
  contact-name: char-crypt inc.
  contact-url: www.char-crypt.org
  dir: ${user.home}/.${app.name}
  db-name: charcrypt
  db-host: localhost
  db-port: 5432
  db-username: postgres
  db-password: postgres
  db-url-prefix: jdbc:postgresql://

spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    type: com.zaxxer.hikari.HikariDataSource
    url: ${app.db-url-prefix}${app.db-host}:${app.db-port}/${app.db-name}
    initialization-mode: never
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    hibernate:
      ddl-auto: none
      show_sql: true
      use_sql_comments: true
      format_sql: true
      generate_statistics: false

  flyway:
    enabled: true
    baseline-on-migrate: true
  config:
    activate:
      on-profile: dev
